version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run: npm rebuild node-sass
      - run: npm run build

      - setup_remote_docker:
                docker_layer_caching:

      - run: |
          docker build -t rsenuatnu.azurecr.io/early-modern-ballot:latest -t rsenuatnu.azurecr.io/early-modern-ballot:$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS rsenuatnu.azurecr.io
          docker push rsenuatnu.azurecr.io/early-modern-ballot:latest
          docker push rsenuatnu.azurecr.io/early-modern-ballot:$CIRCLE_SHA1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: atnu-context
